#!/bin/bash
# ------------------------------------------------------------------
#
#     Scripts/mailcount
#     Description: Script for checking the number of unread mails
#     Author: otiuz Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

MAILDIR="$HOME/.mail/gmail/Inbox/new"
ICON="mail.xbm"
NUMBER=`find $MAILDIR -type f | wc -l`

ICON='^i(/home/otiuz/.xmonad/dzen/icons/xbm8x8/'"$ICON)"
echo "$ICON $NUMBER"
