#!/bin/bash
# ------------------------------------------------------------------
#
#  Scripts/updcount
#  Description: Script for checking the number of updates available
#  Author: otiuz Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

ICON="pacman.xbm"
NUMBER=`pacman -Qu | wc -l`

ICON='^i(/home/otiuz/.xmonad/dzen/icons/xbm8x8/'"$ICON)"
echo "$ICON $NUMBER"
