#!/bin/bash

first_artist=""

while :
do
	new_artist=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 2 "artist"|egrep -v "artist"|egrep -v "array"|cut -b 27-|cut -d '"' -f 1|egrep -v ^$`
	if [ "$new_artist" != "$first_artist" ] 
	then
		first_artist="$new_artist"
		echo "$new_artist"
	fi
	sleep 1
done