#!/bin/bash

first_cover=""

while :
do
	new_cover=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 1 "artUrl"|cut -b 44-|cut -d '"' -f 1|egrep -v ^$)
	if [ "$new_cover" != "$first_cover" ]
	then
		first_cover="$new_cover"
		wget -O ~/scripts/spotify/last_album_pic.png $new_cover
	fi
	sleep 1
done