#!/bin/bash

first_title=""

while :
do
	new_title=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 1 "title"|egrep -v "title"|cut -b 44-|cut -d '"' -f 1|egrep -v ^$`
	if [ "$new_title" != "$first_title" ] 
	then
		first_title="$new_title"
		echo "$new_title"
	fi
	sleep 1
done